### ISSUE TITLE
Integrate test suite with Travis CI

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#16]
We'll need to use Docker on Travis!

http://docs.travis-ci.com/user/docker/

I suspect our `.travis.yml` will look something like this:

```yaml
sudo: required

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose build
  - ./nosetests.sh
```
