### ISSUE TITLE
Document configuration options

### ISSUE THREAD

**Issue by toolness** [GovLab/noi2#245]
We don't do a very good job in the README of documenting configuration options. Under the "Quick Install" section, we provide the following `local_config.yml` template:

```yaml
    MAIL_USERNAME:
    MAIL_PASSWORD:
    NOI_DEPLOY:
    S3_ACCESS_KEY_ID:
    S3_SECRET_ACCESS_KEY:
    DEBUG: False
    SERVER_NAME:
    GA_TRACKING_CODE:
    SECRET_KEY:

    # A list of email addresses to send error reports to.
    ADMINS:
      - admin@example.org
      - error_reports@example.org

    # A list of email addresses corresponding to users who will be
    # able to access the admin panel.
    ADMIN_UI_USERS:
      - admin@example.org

    # A string of the form username:password that will add an extra layer
    # of HTTP Basic Authentication to the admin UI.
    ADMIN_UI_BASIC_AUTH: stay_away:uninvited_guests
```

However, this is really more of a *production* configuration than a development one. `DEBUG` is disabled, for example, and `SECRET_KEY` is left empty, which is going to throw an error on startup if left that way.

It's probably better to document the different config options and perhaps have some nice examples for development and production. The development one should be as short as possible, since the defaults in `config.yml` are already made for development, while the production one can be longer, and should be explicit about what's required for a secure setup.
